import { getDefaultConfig } from '@rainbow-me/rainbowkit';
import { http } from 'wagmi';
import { defineChain } from 'viem';
import {
  injectedWallet,
  rainbowWallet,
  metaMaskWallet,
  coinbaseWallet,
  walletConnectWallet,
  trustWallet,
  ledgerWallet,
  braveWallet,
  phantomWallet,
  okxWallet,
  rabbyWallet,
  zerionWallet,
  bitgetWallet,
  imTokenWallet,
  omniWallet,
  tahoWallet,
  xdefiWallet,
  oneInchWallet,
  tokenaryWallet,
  uniswapWallet,
  safeWallet,
  coreWallet,
  roninWallet,
  frameWallet,
  frontierWallet,
  argentWallet,
  bifrostWallet,
  bitskiWallet,
  bloomWallet,
  clvWallet,
  coin98Wallet,
  dawnWallet,
  enkryptWallet,
  foxWallet,
  krakenWallet,
  kaikasWallet,
  magicEdenWallet,
  mewWallet,
  nestWallet,
  oktoWallet,
  tokenPocketWallet,
  trezorWallet,
  unstoppableWallet,
  binanceWallet,
  bitverseWallet,
  bybitWallet,
  gateWallet,
  kresusWallet,
  subWallet,
  talismanWallet,
} from '@rainbow-me/rainbowkit/wallets';

import { mainnet, polygon, optimism, arbitrum, base } from 'wagmi/chains';

// Define Pepe Unchained V2 network configuration
export const pepeUnchainedV2 = defineChain({
  id: 97741,
  name: 'Pepe Unchained V2',
  nativeCurrency: {
    decimals: 18,
    name: 'PEPU',
    symbol: 'PEPU',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc-pepu-v2-mainnet-0.t.conduit.xyz'],
    },
  },
  blockExplorers: {
    default: { name: 'PepuScan', url: 'https://pepuscan.com' },
  },
  testnet: false,
});

// Enhanced configuration with available wallets
export const config = getDefaultConfig({
  appName: 'Pepu Domain Service',
  projectId: 'c4f79cc821944d9680842e34466bfbd9',
  chains: [mainnet, polygon, optimism, arbitrum, base, pepeUnchainedV2],
  transports: {
    [pepeUnchainedV2.id]: http('https://rpc-pepu-v2-mainnet-0.t.conduit.xyz'),
  },
  wallets: [
    {
      groupName: 'Popular',
      wallets: [
        injectedWallet,
        metaMaskWallet,
        rainbowWallet,
        coinbaseWallet,
        walletConnectWallet,
        trustWallet,
        phantomWallet,
        okxWallet,
        rabbyWallet,
        zerionWallet,
        bitgetWallet,
        uniswapWallet,
      ],
    },
    {
      groupName: 'Hardware',
      wallets: [
        ledgerWallet,
        trezorWallet,
      ],
    },
    {
      groupName: 'Mobile',
      wallets: [
        imTokenWallet,
        tokenPocketWallet,
        coin98Wallet,
        foxWallet,
        mewWallet,
        kaikasWallet,
        magicEdenWallet,
        clvWallet,
        binanceWallet,
        bybitWallet,
        gateWallet,
        subWallet,
      ],
    },
    {
      groupName: 'Browser',
      wallets: [
        braveWallet,
        frameWallet,
        enkryptWallet,
        dawnWallet,
        frontierWallet,
        xdefiWallet,
        oneInchWallet,
        tokenaryWallet,
        safeWallet,
        coreWallet,
        roninWallet,
        argentWallet,
        bitverseWallet,
        bloomWallet,
        bitskiWallet,
        bifrostWallet,
        krakenWallet,
        kresusWallet,
        nestWallet,
        oktoWallet,
        omniWallet,
        tahoWallet,
        talismanWallet,
        unstoppableWallet,
      ],
    },
  ],
  ssr: false,
  multiInjectedProviderDiscovery: true,
});
